version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app2
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx2
    restart: unless-stopped
    ports:
      - "8007:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

# убираем определение db (mysql) и phpmyadmin, чтобы не создавать дубли

networks:
  default:
    name: my_portfolio_default
